# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9005460d4326b9e76caceace1593e5ae89581c88f49945dc43dc660ee0eff5862bf3d944ca8355da539812ccfc322e1c69be80d85152c1c4d46234e852c7b66c

test:
  secret_key_base: 2ab4c8b6b8a22ae57933b67f5b3858b9c4e9045f61c6e2b9ace5cfaf59154a2439872988eb3fa11d48d8040dc971e6d79d482ab16302caa7c80e51784d64f311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
